name: DEV Node.js CI

  on:
    push:
      branches: ["main"]

  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: 'Create env file'
          run: |
            touch .env
            echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
            echo NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} >> .env
            echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
            echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
            echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env
            echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
            echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
            echo MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }} >> .env
            echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env
            echo MYSQL_PORT=${{ secrets.MYSQL_PORT }} >> .env
            cat .env

        - name: "Build project"
          run: |
            yarn install
            yarn build
            rm -r node_modules

        - name: AWS CodeDeploy
          uses: sourcetoad/aws-codedeploy-action@v1
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: ap-northeast-2
            codedeploy_name: dev-crossword-game
            codedeploy_group: dev-crossword
            codedeploy_register_only: false
            s3_bucket: crossword-bucket
            s3_folder: dev
            max_polling_iterations: 0
            directory: ./